version: "2"

services:
  sarueframework_orm_dev_postgres:
    container_name: sarueframework_orm_dev_postgres
    image: postgres:16.2
    environment:
      POSTGRES_PASSWORD: sarue
    volumes:
      - ./db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
